spring:
  application:
    name: springwithkafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: shcaselasttest
  datasource:
    password: 7asbaw2sqn
    username: root
    url: jdbc:mysql://localhost:3306/package_directory?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081